FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /src
COPY . .
RUN dotnet build EthnoWearDB.sqlproj \
    --configuration Release \
    --output /out

FROM mcr.microsoft.com/dotnet/sdk:8.0

RUN dotnet tool install \
    --tool-path /tools \
    microsoft.sqlpackage

WORKDIR /app
COPY --from=build /out/EthnoWearDB.dacpac /app/EthnoWearDB.dacpac
COPY docker/migrate.sh /usr/local/bin/ethnowear-db-migrate

RUN chmod 0555 /usr/local/bin/ethnowear-db-migrate

ENTRYPOINT ["/usr/local/bin/ethnowear-db-migrate"]
