SELECT TOP (1000) [Id]
      ,[SourceReferenceId]
      ,[ChunkType]
      ,[OntologyIri]
      ,[OntologyLocalName]
      ,[Language]
      ,[Content]
      ,[EmbeddingModel]
      ,[EmbeddingId]
      ,[CreatedAt]
      ,[UpdatedAt]
  FROM [EthnoWear].[ethnowear].[KnowledgeChunks]