package fmi.ethnowear.application.dto.worker;

public record WorkerResourceLimitsDetails(
        long maximumInputBytes,
        int maximumPageCount,
        int renderDpi,
        int maximumPixelWidth,
        int maximumPixelHeight,
        long maximumPagePixels,
        long maximumRenditionBytes,
        int maximumOcrTextCharacters,
        long maximumOcrOutputBytes,
        long maximumOcrContextBytes,
        long maximumQualityAssessmentPayloadBytes,
        int maximumQualitySignals,
        int maximumQualitySignalTypeCharacters,
        int maximumQualitySignalTextCharacters,
        int maximumQualitySummaryCharacters,
        int maximumQualityLimitationsCharacters,
        int maximumQualityMessageCharacters,
        long maximumVisionAssessmentPayloadBytes,
        int maximumVisionSuggestionCharacters,
        int maximumVisionIssuesJsonCharacters,
        int maximumVisionIssues,
        int maximumVisionUncertainPassages,
        int maximumVisionIssueCodeCharacters,
        int maximumVisionExcerptCharacters,
        int maximumVisionReasonCharacters,
        int maximumVisionModelNameCharacters,
        int maximumVisionModelVersionCharacters,
        int maximumVisionPromptVersionCharacters,
        int maximumIndexingContentCharacters,
        int maximumEmbeddingDimensions,
        int maximumEmbeddingModelCharacters,
        int maximumVectorCollectionCharacters,
        int maximumVectorPointIdCharacters,
        int maximumFigureCandidates,
        int maximumFigureCaptionCharacters,
        int maximumPrintedFigureNumberCharacters,
        long maximumFigureCropBytes,
        long jobTimeoutSeconds,
        long heartbeatIntervalSeconds,
        long maximumLeaseSeconds
) {

    public WorkerResourceLimitsDetails(
            long maximumInputBytes,
            int maximumPageCount,
            int renderDpi,
            int maximumPixelWidth,
            int maximumPixelHeight,
            long maximumPagePixels,
            long maximumRenditionBytes,
            int maximumOcrTextCharacters,
            long maximumOcrOutputBytes,
            long jobTimeoutSeconds,
            long heartbeatIntervalSeconds,
            long maximumLeaseSeconds
    ) {
        this(
                maximumInputBytes,
                maximumPageCount,
                renderDpi,
                maximumPixelWidth,
                maximumPixelHeight,
                maximumPagePixels,
                maximumRenditionBytes,
                maximumOcrTextCharacters,
                maximumOcrOutputBytes,
                16L * 1024 * 1024,
                1024L * 1024,
                100,
                100,
                500,
                1000,
                1000,
                1000,
                10L * 1024 * 1024,
                2000000,
                4000,
                100,
                100,
                100,
                500,
                1000,
                100,
                100,
                100,
                10000,
                4096,
                100,
                150,
                255,
                100,
                2000,
                100,
                25L * 1024 * 1024,
                jobTimeoutSeconds,
                heartbeatIntervalSeconds,
                maximumLeaseSeconds
        );
    }

    public WorkerResourceLimitsDetails(
            long maximumInputBytes,
            int maximumPageCount,
            int renderDpi,
            int maximumPixelWidth,
            int maximumPixelHeight,
            long maximumPagePixels,
            long maximumRenditionBytes,
            int maximumOcrTextCharacters,
            long maximumOcrOutputBytes,
            long maximumOcrContextBytes,
            long maximumQualityAssessmentPayloadBytes,
            int maximumQualitySignals,
            int maximumQualitySignalTypeCharacters,
            int maximumQualitySignalTextCharacters,
                int maximumQualitySummaryCharacters,
                int maximumQualityLimitationsCharacters,
                int maximumQualityMessageCharacters,
            long jobTimeoutSeconds,
            long heartbeatIntervalSeconds,
            long maximumLeaseSeconds
    ) {
        this(
                maximumInputBytes,
                maximumPageCount,
                renderDpi,
                maximumPixelWidth,
                maximumPixelHeight,
                maximumPagePixels,
                maximumRenditionBytes,
                maximumOcrTextCharacters,
                maximumOcrOutputBytes,
                maximumOcrContextBytes,
                maximumQualityAssessmentPayloadBytes,
                maximumQualitySignals,
                maximumQualitySignalTypeCharacters,
                maximumQualitySignalTextCharacters,
                maximumQualitySummaryCharacters,
                maximumQualityLimitationsCharacters,
                maximumQualityMessageCharacters,
                10L * 1024 * 1024,
                2000000,
                4000,
                100,
                100,
                100,
                500,
                1000,
                100,
                100,
                100,
                10000,
                4096,
                100,
                150,
                255,
                100,
                2000,
                100,
                25L * 1024 * 1024,
                jobTimeoutSeconds,
                heartbeatIntervalSeconds,
                maximumLeaseSeconds
        );
    }
}
