from ethnowear_worker_common.api.models import ResourceLimits


def limits() -> ResourceLimits:
    return ResourceLimits.model_validate({
        "maximumInputBytes": 25_000_000,
        "maximumPageCount": 2_000,
        "renderDpi": 300,
        "maximumPixelWidth": 20_000,
        "maximumPixelHeight": 20_000,
        "maximumPagePixels": 100_000_000,
        "maximumRenditionBytes": 25_000_000,
        "maximumOcrTextCharacters": 1_000_000,
        "maximumOcrOutputBytes": 10_000_000,
        "maximumOcrContextBytes": 16_000_000,
        "maximumQualityAssessmentPayloadBytes": 1_000_000,
        "maximumQualitySignals": 100,
        "maximumQualitySignalTypeCharacters": 100,
        "maximumQualitySignalTextCharacters": 500,
        "maximumQualitySummaryCharacters": 1_000,
        "maximumQualityLimitationsCharacters": 1_000,
        "maximumQualityMessageCharacters": 1_000,
        "maximumVisionAssessmentPayloadBytes": 10_000_000,
        "maximumVisionSuggestionCharacters": 2_000_000,
        "maximumVisionIssuesJsonCharacters": 4_000,
        "maximumVisionIssues": 100,
        "maximumVisionUncertainPassages": 100,
        "maximumVisionIssueCodeCharacters": 100,
        "maximumVisionExcerptCharacters": 500,
        "maximumVisionReasonCharacters": 1_000,
        "maximumVisionModelNameCharacters": 100,
        "maximumVisionModelVersionCharacters": 100,
        "maximumVisionPromptVersionCharacters": 100,
        "maximumIndexingContentCharacters": 10_000,
        "maximumEmbeddingDimensions": 4_096,
        "maximumEmbeddingModelCharacters": 100,
        "maximumVectorCollectionCharacters": 150,
        "maximumVectorPointIdCharacters": 255,
        "jobTimeoutSeconds": 1_800,
        "heartbeatIntervalSeconds": 30,
        "maximumLeaseSeconds": 300,
    })
