import i18n from '../../app/i18n'
i18n.addResourceBundle('bg', 'chatDesign', {
 historyLogin: 'Вход с Google', historyLoginMessage: 'Влезте с Google за история на разговорите в профила ви и достъп от други устройства. Като гост историята е само за текущата сесия.',
 fontSize: 'Размер на текста', smallerText: 'Намали текста', largerText: 'Увеличи текста', resetText: 'Върни размера на 100%',
 nav: 'Асистент', subtitle: 'Истории, вплетени в шевици', question: 'Какво искате да откриете?', intro: 'Мотиви, техники и традиции на българската шевица.', new: 'Нов разговор', conversations: 'Разговори', options: 'Опции', optionsFor: 'Опции за {{title}}', rename: 'Преименувай', delete: 'Изтрий', renameTitle: 'Преименуване на разговор', conversationTitle: 'Заглавие', cancelAction: 'Отказ', saveRename: 'Запази', deleteTitle: 'Изтриване на разговор', deleteDescription: 'Разговорът „{{title}}“ и цялата му история ще бъдат изтрити без възможност за възстановяване.', confirmDelete: 'Изтрий разговора',
 placeholder: 'Попитайте за българската шевица…', queuePlaceholder: 'Добавете следващ въпрос към опашката…', send: 'Добави съобщение', addToQueue: 'Добави към опашката', queue: 'Следващи въпроси', queuedCount: '{{count}} в опашката', queuedPosition: 'Следващ №{{position}}', editQueued: 'Редактирай въпроса', removeQueued: 'Премахни от опашката', saveQueueEdit: 'Запази', answeredIn: ' · отговор за {{duration}}', grounded: 'Отговори от проверени източници', processing: 'Подготвям отговора', historyOwner: 'Историята е свързана с текущия профил или гост сесия', you: 'Вие', open: 'Отвори бърз разговор', close: 'Затвори разговора', full: 'Продължи в разговора', archive: 'Разгледай архива', history: 'Покажи разговорите', copy: 'Копирай съобщението', copied: 'Копирано', copyAnswer: 'Копирай отговора', cancel: 'Спри', cancelled: 'Заявката беше спряна.', retry: 'Опитай отново', failed: 'Отговорът не беше завършен', sources: 'Източници', related: 'Свързани резултати', media: 'Свързани изображения', mediaItem: 'Архивно изображение', archiveResult: 'Архивен запис', archiveActions: 'Действия за архива', insufficientEvidence: 'Няма достатъчно проверени данни за пълен отговор.', region: 'Региони', motif: 'Мотиви', technique: 'Техники', color: 'Цветове',
 p1: 'Какво отличава шопската шевица?', p2: 'Къде се среща мотивът „дърво на живота“?', p3: 'Как се изпълнява кръстат бод?', p4: 'Какви цветове се срещат в българските шевици?',
 stages: { RECEIVED: 'Въпросът е получен', RESOLVING_ENTITIES: 'Разпознавам понятията', READING_ONTOLOGY: 'Проверявам онтологията', SEARCHING_ARCHIVE: 'Търся в архива', RETRIEVING_SOURCES: 'Преглеждам одобрени източници', REASONING: 'Изчислявам връзките', INTERPRETING: 'Подреждам резултатите', GENERATING_ANSWER: 'Съставям отговора', VALIDATING_ANSWER: 'Проверявам отговора' },
 entities: { REGION: 'Регион', REGIONAL_EMBROIDERY: 'Регионална шевица', REGIONAL_MOTIF: 'Регионален мотив', MOTIF: 'Мотив', ORNAMENT: 'Орнамент', TECHNIQUE: 'Техника', COLOR: 'Цвят' },
 errors: { CONVERSATION_VALIDATION: 'Въпросът е празен, прекалено дълъг или невалиден.', CONVERSATION_OWNER_REQUIRED: 'Необходима е активна гост сесия или публичен профил.', CONVERSATION_NOT_FOUND: 'Разговорът вече не е наличен.', CONVERSATION_TURN_NOT_FOUND: 'Заявката вече не е налична.', CONVERSATION_REQUEST_CONFLICT: 'Тази заявка вече е обработена с различни данни.', CONVERSATION_TURN_ACTIVE: 'Изчакайте текущият отговор да приключи.', CONVERSATION_TURN_NOT_CANCELLABLE: 'Тази заявка вече не може да бъде спряна.', CONVERSATION_RATE_LIMITED: 'Изпратени са твърде много заявки. Опитайте отново след малко.', CONVERSATION_UNSAFE_INPUT: 'Въпросът не може да бъде обработен безопасно.', CONVERSATION_OUT_OF_SCOPE: 'Попитайте за български шевици, мотиви, техники или архивни източници.', CONVERSATION_PROCESSING_FAILED: 'Възникна временен проблем при подготовката на отговора.', PUBLIC_AUTH_REQUIRED: 'Необходима е публична сесия.', PUBLIC_ACCESS_DENIED: 'Публичната сесия няма достъп до този разговор.' }
})
i18n.addResourceBundle('en', 'chatDesign', {
 historyLogin: 'Sign in with Google', historyLoginMessage: 'Sign in with Google to keep conversation history in your account and access it across devices. Guest history is limited to the current session.',
 fontSize: 'Text size', smallerText: 'Decrease text size', largerText: 'Increase text size', resetText: 'Reset text size to 100%',
 nav: 'Chat', subtitle: 'Stories woven in embroidery', question: 'What would you like to discover?', intro: 'Motifs, techniques and Bulgarian embroidery traditions.', new: 'New conversation', conversations: 'Conversations', options: 'Options', optionsFor: 'Options for {{title}}', rename: 'Rename', delete: 'Delete', renameTitle: 'Rename conversation', conversationTitle: 'Title', cancelAction: 'Cancel', saveRename: 'Save', deleteTitle: 'Delete conversation', deleteDescription: '“{{title}}” and its complete history will be permanently deleted.', confirmDelete: 'Delete conversation',
 placeholder: 'Ask about Bulgarian embroidery…', queuePlaceholder: 'Add the next question to the queue…', send: 'Add message', addToQueue: 'Add to queue', queue: 'Next questions', queuedCount: '{{count}} queued', queuedPosition: 'Next #{{position}}', editQueued: 'Edit queued question', removeQueued: 'Remove from queue', saveQueueEdit: 'Save', answeredIn: ' · answered in {{duration}}', grounded: 'Answers from verified sources', processing: 'Preparing the answer', historyOwner: 'History belongs to the current profile or guest session', you: 'You', open: 'Open quick chat', close: 'Close chat', full: 'Continue in full chat', archive: 'Explore the archive', history: 'Show conversations', copy: 'Copy message', copied: 'Copied', copyAnswer: 'Copy answer', cancel: 'Cancel', cancelled: 'The request was cancelled.', retry: 'Try again', failed: 'The answer could not be completed', sources: 'Sources', related: 'Related results', media: 'Related images', mediaItem: 'Archive image', archiveResult: 'Archive item', archiveActions: 'Archive actions', insufficientEvidence: 'There is not enough verified evidence for a complete answer.', region: 'Regions', motif: 'Motifs', technique: 'Techniques', color: 'Colors',
 p1: 'What makes Shopluk embroidery distinctive?', p2: 'Where does the tree of life motif appear?', p3: 'How is cross stitch made?', p4: 'Which colors appear in Bulgarian embroidery?',
 stages: { RECEIVED: 'Question received', RESOLVING_ENTITIES: 'Resolving concepts', READING_ONTOLOGY: 'Reading the ontology', SEARCHING_ARCHIVE: 'Searching the archive', RETRIEVING_SOURCES: 'Reading approved sources', REASONING: 'Comparing relationships', INTERPRETING: 'Organizing results', GENERATING_ANSWER: 'Writing the answer', VALIDATING_ANSWER: 'Validating the answer' },
 entities: { REGION: 'Region', REGIONAL_EMBROIDERY: 'Regional embroidery', REGIONAL_MOTIF: 'Regional motif', MOTIF: 'Motif', ORNAMENT: 'Ornament', TECHNIQUE: 'Technique', COLOR: 'Color' },
 errors: { CONVERSATION_VALIDATION: 'The question is empty, too long, or invalid.', CONVERSATION_OWNER_REQUIRED: 'An active guest session or public profile is required.', CONVERSATION_NOT_FOUND: 'This conversation is no longer available.', CONVERSATION_TURN_NOT_FOUND: 'This request is no longer available.', CONVERSATION_REQUEST_CONFLICT: 'This request was already processed with different data.', CONVERSATION_TURN_ACTIVE: 'Wait for the current answer to finish.', CONVERSATION_TURN_NOT_CANCELLABLE: 'This request can no longer be cancelled.', CONVERSATION_RATE_LIMITED: 'Too many requests were sent. Try again shortly.', CONVERSATION_UNSAFE_INPUT: 'This question cannot be processed safely.', CONVERSATION_OUT_OF_SCOPE: 'Ask about Bulgarian embroidery, motifs, techniques, or archive sources.', CONVERSATION_PROCESSING_FAILED: 'A temporary problem occurred while preparing the answer.', PUBLIC_AUTH_REQUIRED: 'A public session is required.', PUBLIC_ACCESS_DENIED: 'The public session cannot access this conversation.' }
})
i18n.addResources('bg', 'chatDesign', {
 unavailable: 'Разговорът не е достъпен',
 'errors.CONVERSATION_OLLAMA_UNAVAILABLE': 'Услугата за генериране на отговори (Ollama) не е достъпна.',
 'errors.CONVERSATION_RAG_UNAVAILABLE': 'Търсенето в проверените източници (RAG) не е достъпно.'
 , 'errors.CONVERSATION_GROUNDING_FAILED': 'Отговорът не премина проверката спрямо източниците. Опитайте да уточните въпроса.'
})
i18n.addResources('en', 'chatDesign', {
 unavailable: 'Chat unavailable',
 'errors.CONVERSATION_OLLAMA_UNAVAILABLE': 'The answer generation service (Ollama) is unavailable.',
 'errors.CONVERSATION_RAG_UNAVAILABLE': 'Verified-source retrieval (RAG) is unavailable.'
 , 'errors.CONVERSATION_GROUNDING_FAILED': 'The answer did not pass source validation. Try making the question more specific.'
})
